export const COLLECTIONS = {
  APPUSERS: "appusers",
  ATTENDANCE: "attendance",
  BRANCHES: "branches",
  CROWD_FORECASTS: "crowdForecasts",
  MEMBERS: "members",
  MEMBER_SESSIONS: "memberSessions",
  MEMBER_SESSION_REDEMPTIONS: "memberSessionRedemptions",
  TENANTS: "tenants",
  NOTIFICATIONS: "notifications",
  PAYMENTS: "payments",
  SUBSCRIPTIONS: "subscriptions",
  USERS: "users",
  WORKOUT_ASSIGNMENTS: "workoutAssignments",
  INVITES: "invites",
  JOIN_REQUESTS: "joinRequests",
  PLANS: "plans",
  USER_HEALTH: "userHealth",
  FITNESS: "fitness",
  DIET: "diet",
  TRACKING: "tracking",
} as const;
